version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: "Difference in ddl"
          command: |
            git diff --no-commit-id --name-only -r master | sort -u >  files
            while read file; do
              if [[ "$file" == *"ddl/"* ]]; then
                python roll_out.py $file $(cat $file)
              fi
            done <files

workflows:
  build-workflow:
    jobs:
      - build
#      - build:
#          filters:
#            branches:
#              only: master # only deploy when on master
