version: 2.1

jobs:
  build:
    environment:
      PGUSER: $PGUSER
      PGPASSWORD: $PGPASSWORD
      PGDATABASE: $PGDATABASE
      PGPORT: $PGPORT
      PGHOST: $PGHOST
    docker:
      - image: yaropv1/circleci
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: "Difference in ddl"
          command: |
            git diff --no-commit-id --name-only -r master | sort -u >  files
            cat files | python roll_out.py

workflows:
  build-workflow:
    jobs:
      - build
#      - build:
#          filters:
#            branches:
#              only: master # only deploy when on master
