version: 2.1

jobs:
  build:
    environment:
      PGUSER: user
      PGPASSWORD: password
      PGDATABASE: database
      PGPORT: port
      PGHOST: host
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: "Install pcycorg2-binary"
          command: pip install psycopg2-binary
      - run:
          name: "Difference in ddl"
          command: |
            git diff --no-commit-id --name-only -r master | sort -u >  files
            echo $(cat $files)

workflows:
  build-workflow:
    jobs:
      - build
#      - build:
#          filters:
#            branches:
#              only: master # only deploy when on master
